# Generated by Django 2.1.3 on 2018-11-29 21:17

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=128, verbose_name='Name, surname, fathers.')),
                ('position', models.CharField(max_length=50)),
                ('date_of_recruit', models.DateTimeField()),
                ('salary', models.PositiveIntegerField(default=0)),
                ('photo', models.ImageField(help_text='jpg/png - file', upload_to='', verbose_name='Photo')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('chief', mptt.fields.TreeForeignKey(blank=True, default=None, max_length=128, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='under_emp', to='emp.Employee', verbose_name='chief')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
