# Generated by Django 2.1.3 on 2018-11-30 08:51

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='chief',
            field=mptt.fields.TreeForeignKey(blank=True, max_length=128, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='under_emp', to='emp.Employee', verbose_name='chief'),
        ),
    ]
