# Generated by Django 2.1.3 on 2018-11-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0003_auto_20181130_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='full_name',
            field=models.CharField(max_length=128, verbose_name='surname, name, fathers'),
        ),
    ]
