# Generated by Django 2.1.3 on 2018-11-30 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0004_auto_20181130_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='position',
            new_name='emp_position',
        ),
    ]
