# Generated by Django 2.1.3 on 2018-12-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0006_auto_20181130_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='full_name',
            field=models.CharField(db_index=True, max_length=128, unique=True, verbose_name='surname, name, fathers'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=12, verbose_name='salary'),
        ),
    ]
